(() => {
 const PIN='laberinto_session_pin', API='https://ufsxdlmnjuaymdszyjue.supabase.co/functions/v1/laberinto-api';
 const frames=[
  {id:'productexplosion',name:'Product Explosion',desc:'Producto protagonista con sus ingredientes reales separados alrededor.',needs:'ingredients'},
  {id:'magazine',name:'Magazine',desc:'Composición editorial con dirección de arte y espacio para titular.',needs:'context'},
  {id:'hero',name:'Hero Product',desc:'Producto limpio y protagonista, pensado para publicidad.',needs:'context'},
  {id:'ingredients',name:'Ingredientes',desc:'Producto acompañado únicamente por ingredientes confirmados.',needs:'ingredients'},
  {id:'creative-context',name:'Contexto creativo',desc:'Sitúa el producto en una escena conceptual coherente con la marca.',needs:'context'},
  {id:'poster',name:'Poster',desc:'Afiche visual con producto protagonista y espacio para texto.',needs:'context'}
 ];
 const css=document.createElement('style');css.textContent=`.studio-view{display:none}.studio-view.active{display:block}.frame-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.frame-card{border:1px solid #e7dfd2;background:#fff;border-radius:16px;padding:16px;text-align:left;cursor:pointer}.frame-card.active{outline:2px solid #111827}.frame-card strong,.frame-card span{display:block}.frame-card span{font-size:.86rem;color:#756b5d;margin-top:6px}.studio-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.studio-drop{border:2px dashed #d8cfc0;border-radius:16px;min-height:260px;display:grid;place-items:center;padding:18px;text-align:center}.studio-preview{max-width:100%;max-height:360px;border-radius:14px}.ai-question{background:#f7f2ea;border-radius:14px;padding:14px;margin-top:12px}.ai-question textarea{width:100%;margin-top:8px}.studio-status{margin-top:10px;font-size:.9rem;color:#62594d}@media(max-width:760px){.frame-grid{grid-template-columns:1fr 1fr}.studio-grid{grid-template-columns:1fr}}`;document.head.appendChild(css);
 function boot(){const tabs=document.querySelector('.app-tabs'),settings=document.querySelector('#settingsView'),publicador=document.querySelector('main.main-view');if(!tabs||!settings||!publicador)return setTimeout(boot,150);if(document.querySelector('#tabStudio'))return;
  const planner=document.querySelector('#tabPlanner'),btn=document.createElement('button');btn.id='tabStudio';btn.className='app-tab';btn.type='button';btn.textContent='Estudio IA';planner?.insertAdjacentElement('afterend',btn)||tabs.insertBefore(btn,document.querySelector('#tabSettings'));
  const view=document.createElement('main');view.id='studioView';view.className='shell studio-view';view.innerHTML=`<section class="panel"><div class="panel-heading"><div><span class="eyebrow">ESTUDIO IA</span><h2>Crear y optimizar imágenes</h2></div></div><p class="helper">Sube una foto, elige un frame y deja que la IA pregunte lo que no puede saber antes de crear. Nunca debe inventar ingredientes ni modificar el producto sin confirmación.</p><div class="studio-grid"><div><label>Marca<select id="studioBrand"><option value="adria-sushi">Adrià Sushi</option><option value="adria-sangucheria">Sanguchería Adrià</option><option value="pet">Adrià PET</option><option value="chef-rafael">Chef Rafael</option><option value="laberinto-digital">Laberinto Digital</option></select></label><div id="studioDrop" class="studio-drop"><div><strong>Subir imagen</strong><p>Toca aquí para elegir el producto o fotografía.</p></div><input id="studioFile" type="file" accept="image/jpeg,image/png,image/webp" hidden></div></div><div><span class="eyebrow">FRAME</span><div id="frameGrid" class="frame-grid">${frames.map((f,i)=>`<button type="button" class="frame-card ${i===0?'active':''}" data-frame="${f.id}"><strong>/${f.id}</strong><span>${f.desc}</span></button>`).join('')}</div></div></div><div id="studioQuestion" class="ai-question" hidden><strong id="studioQuestionTitle">Necesito confirmar algo</strong><p id="studioQuestionText"></p><textarea id="studioAnswer" rows="3" placeholder="Escribe aquí la información que falta…"></textarea></div><label style="margin-top:14px">Idea opcional<textarea id="studioIdea" rows="2" placeholder="Ej: promocionar este producto, fondo oscuro, mantener el sushi idéntico…"></textarea></label><div class="planner-actions"><button id="studioAnalyze" class="btn secondary" type="button">Analizar antes de crear</button><button id="studioGenerate" class="btn primary" type="button" disabled>Generar imagen</button></div><div id="studioStatus" class="studio-status">Primero sube una imagen.</div></section>`;settings.insertAdjacentElement('beforebegin',view);
  let selected=frames[0],file=null;
  const hide=()=>view.classList.remove('active');document.querySelector('#tabPublicador')?.addEventListener('click',hide);document.querySelector('#tabPlanner')?.addEventListener('click',hide);document.querySelector('#tabSettings')?.addEventListener('click',hide);
  btn.onclick=()=>{publicador.classList.add('settings-hidden');settings.classList.remove('active');document.querySelector('#plannerView')?.classList.remove('active');view.classList.add('active');document.querySelectorAll('.app-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');};
  document.querySelectorAll('.frame-card').forEach(x=>x.onclick=()=>{document.querySelectorAll('.frame-card').forEach(y=>y.classList.remove('active'));x.classList.add('active');selected=frames.find(f=>f.id===x.dataset.frame)||frames[0];document.querySelector('#studioQuestion').hidden=true;document.querySelector('#studioGenerate').disabled=true;});
  const input=document.querySelector('#studioFile'),drop=document.querySelector('#studioDrop');drop.onclick=()=>input.click();input.onchange=()=>{file=input.files?.[0]||null;if(!file)return;const u=URL.createObjectURL(file);drop.innerHTML=`<img class="studio-preview" src="${u}" alt="Vista previa"><input id="studioFileGhost" hidden>`;document.querySelector('#studioStatus').textContent='Imagen lista. Pulsa “Analizar antes de crear”.';};
  document.querySelector('#studioAnalyze').onclick=()=>{if(!file){document.querySelector('#studioStatus').textContent='Sube primero una imagen.';return;}const q=document.querySelector('#studioQuestion'),title=document.querySelector('#studioQuestionTitle'),text=document.querySelector('#studioQuestionText');q.hidden=false;if(selected.needs==='ingredients'){title.textContent='La IA necesita tu confirmación';text.textContent='Para este frame necesito saber los ingredientes reales que quieres mostrar. Escríbelos tal como corresponden al producto. Si alguno no debe aparecer, indícalo. La imagen original servirá de referencia, pero no voy a inventar lo que no pueda identificar.';}else{title.textContent='¿Hay algo que la imagen no me pueda decir?';text.textContent='Confirma el producto y cualquier dato importante que deba respetar: qué es, qué no debo cambiar, contexto deseado o elementos que no deben aparecer.';}document.querySelector('#studioGenerate').disabled=false;document.querySelector('#studioStatus').textContent='Completa solo lo que la IA no pueda deducir con seguridad. Esta primera versión deja preparado el briefing visual.';};
  document.querySelector('#studioGenerate').onclick=()=>{const ans=document.querySelector('#studioAnswer').value.trim();if(selected.needs==='ingredients'&&!ans){document.querySelector('#studioStatus').textContent='Para este frame necesito los ingredientes confirmados antes de generar.';return;}document.querySelector('#studioStatus').textContent=`Brief listo para /${selected.id}. Siguiente etapa: conectar generación de imágenes y enviar el resultado directo al Publicador.`;};
 }
 boot();
})();