(() => {
 const PIN='laberinto_session_pin', API='https://ufsxdlmnjuaymdszyjue.supabase.co/functions/v1/image-studio';
 const frames=[
  {id:'productexplosion',name:'Product Explosion',desc:'Producto protagonista con sus ingredientes reales separados alrededor.',needs:'ingredients'},
  {id:'magazine',name:'Magazine',desc:'Composición editorial con dirección de arte y espacio para titular.',needs:'context'},
  {id:'hero',name:'Hero Product',desc:'Producto limpio y protagonista, pensado para publicidad.',needs:'context'},
  {id:'ingredients',name:'Ingredientes',desc:'Producto acompañado únicamente por ingredientes confirmados.',needs:'ingredients'},
  {id:'creative-context',name:'Contexto creativo',desc:'Sitúa el producto en una escena creativa coherente con la marca.',needs:'context'},
  {id:'poster',name:'Poster',desc:'Afiche visual con producto protagonista y espacio para texto.',needs:'context'}
 ];
 const css=document.createElement('style');css.textContent=`.studio-view{display:none}.studio-view.active{display:block}.frame-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.frame-card{border:1px solid #e7dfd2;background:#fff;border-radius:16px;padding:16px;text-align:left;cursor:pointer}.frame-card.active{outline:2px solid #111827}.frame-card strong,.frame-card span{display:block}.frame-card span{font-size:.86rem;color:#756b5d;margin-top:6px}.studio-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.studio-drop{border:2px dashed #d8cfc0;border-radius:16px;min-height:260px;display:grid;place-items:center;padding:18px;text-align:center;cursor:pointer}.studio-preview{max-width:100%;max-height:420px;border-radius:14px}.ai-question{background:#f7f2ea;border-radius:14px;padding:14px;margin-top:12px}.ai-question textarea{width:100%;margin-top:8px}.studio-status{margin-top:10px;font-size:.9rem;color:#62594d}.studio-result{margin-top:16px;display:none}.studio-result.active{display:block}.studio-compare{display:grid;grid-template-columns:1fr 1fr;gap:12px}.studio-compare figure{margin:0;border:1px solid #e7dfd2;border-radius:16px;padding:10px;background:#fff}.studio-compare figcaption{font-size:.78rem;font-weight:800;margin-bottom:8px}.studio-compare img{width:100%;border-radius:12px;display:block}.studio-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.studio-inspection{font-size:.84rem;color:#62594d;margin-top:8px}.studio-loading{opacity:.65;pointer-events:none}@media(max-width:760px){.frame-grid{grid-template-columns:1fr 1fr}.studio-grid,.studio-compare{grid-template-columns:1fr}}`;document.head.appendChild(css);
 const postForm=async(action,file,extra={})=>{const fd=new FormData();fd.append('action',action);fd.append('pin',sessionStorage.getItem(PIN)||'');fd.append('file',file,file.name||'input.jpg');Object.entries(extra).forEach(([k,v])=>fd.append(k,String(v??'')));const r=await fetch(API,{method:'POST',body:fd}),d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||'Error de conexión');e.detail=d.detail||'';throw e;}return d;};
 function boot(){const tabs=document.querySelector('.app-tabs'),settings=document.querySelector('#settingsView'),publicador=document.querySelector('main.main-view');if(!tabs||!settings||!publicador)return setTimeout(boot,150);if(document.querySelector('#tabStudio'))return;
  const planner=document.querySelector('#tabPlanner'),btn=document.createElement('button');btn.id='tabStudio';btn.className='app-tab';btn.type='button';btn.textContent='Estudio IA';planner?.insertAdjacentElement('afterend',btn)||tabs.insertBefore(btn,document.querySelector('#tabSettings'));
  const view=document.createElement('main');view.id='studioView';view.className='shell studio-view';view.innerHTML=`<section class="panel"><div class="panel-heading"><div><span class="eyebrow">ESTUDIO IA</span><h2>Crear y optimizar imágenes</h2></div></div><p class="helper">Sube una foto, elige un frame y deja que la IA confirme lo que no puede saber antes de crear. Nunca debe inventar ingredientes ni modificar el producto sin confirmación.</p><div class="studio-grid"><div><label>Marca<select id="studioBrand"><option value="adria-sushi">Adrià Sushi</option><option value="adria-sangucheria">Sanguchería Adrià</option><option value="pet">Adrià PET</option><option value="chef-rafael">Chef Rafael</option><option value="laberinto-digital">Laberinto Digital</option></select></label><div id="studioDrop" class="studio-drop"><div id="studioSourceWrap"><strong>Subir imagen</strong><p>Toca aquí para elegir el producto o fotografía.</p></div><input id="studioFile" type="file" accept="image/jpeg,image/png,image/webp" hidden></div></div><div><span class="eyebrow">FRAME</span><div id="frameGrid" class="frame-grid">${frames.map((f,i)=>`<button type="button" class="frame-card ${i===0?'active':''}" data-frame="${f.id}"><strong>/${f.id}</strong><span>${f.desc}</span></button>`).join('')}</div></div></div><div id="studioQuestion" class="ai-question" hidden><strong id="studioQuestionTitle">Necesito confirmar algo</strong><p id="studioQuestionText"></p><div id="studioInspection" class="studio-inspection"></div><textarea id="studioAnswer" rows="3" placeholder="Escribe aquí la información que falta…"></textarea></div><label style="margin-top:14px">Idea opcional<textarea id="studioIdea" rows="2" placeholder="Ej: fondo oscuro, mantener el sushi idéntico, escena de barrio…"></textarea></label><div class="studio-actions"><button id="studioAnalyze" class="btn secondary" type="button">Analizar antes de crear</button><button id="studioGenerate" class="btn primary" type="button" disabled>Generar imagen</button></div><div id="studioStatus" class="studio-status">Primero sube una imagen.</div><div id="studioResult" class="studio-result"><div class="studio-compare"><figure><figcaption>ORIGINAL</figcaption><img id="studioOriginalPreview" alt="Imagen original"></figure><figure><figcaption>RESULTADO IA</figcaption><img id="studioGeneratedPreview" alt="Imagen generada"></figure></div><div class="studio-actions"><button id="studioRegenerate" class="btn secondary" type="button">Regenerar</button><button id="studioUse" class="btn primary" type="button">Usar en publicación</button></div></div></section>`;settings.insertAdjacentElement('beforebegin',view);
  let selected=frames[0],file=null,inspection=null,result=null,sourceUrl='';
  const $=s=>view.querySelector(s),status=t=>$('#studioStatus').textContent=t;
  const resetResult=()=>{result=null;$('#studioResult').classList.remove('active');$('#studioGenerate').disabled=true;};
  const hide=()=>view.classList.remove('active');document.querySelector('#tabPublicador')?.addEventListener('click',hide);document.querySelector('#tabPlanner')?.addEventListener('click',hide);document.querySelector('#tabSettings')?.addEventListener('click',hide);
  btn.onclick=()=>{publicador.classList.add('settings-hidden');settings.classList.remove('active');document.querySelector('#plannerView')?.classList.remove('active');view.classList.add('active');document.querySelectorAll('.app-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');};
  $('#frameGrid').querySelectorAll('.frame-card').forEach(x=>x.onclick=()=>{view.querySelectorAll('.frame-card').forEach(y=>y.classList.remove('active'));x.classList.add('active');selected=frames.find(f=>f.id===x.dataset.frame)||frames[0];inspection=null;$('#studioQuestion').hidden=true;$('#studioAnswer').value='';resetResult();if(file)status(`Frame /${selected.id} elegido. Vuelve a analizar antes de crear.`);});
  const input=$('#studioFile'),drop=$('#studioDrop');drop.onclick=e=>{if(e.target===input)return;input.click();};input.onchange=()=>{file=input.files?.[0]||null;if(!file)return;if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(file);$('#studioSourceWrap').innerHTML=`<img class="studio-preview" src="${sourceUrl}" alt="Vista previa original"><p class="helper">Toca la imagen para cambiarla</p>`;$('#studioOriginalPreview').src=sourceUrl;inspection=null;$('#studioQuestion').hidden=true;$('#studioAnswer').value='';resetResult();status('Imagen lista. Pulsa “Analizar antes de crear”.');};
  async function inspect(){if(!file){status('Sube primero una imagen.');return;}const b=$('#studioAnalyze');b.disabled=true;view.classList.add('studio-loading');status('La IA está revisando el producto y buscando qué necesita confirmar…');try{const d=await postForm('inspect',file,{brand_id:$('#studioBrand').value,frame:selected.id,idea:$('#studioIdea').value});inspection=d.inspection||{};const visible=Array.isArray(inspection.visible_elements)?inspection.visible_elements.join(', '):'';$('#studioInspection').textContent=[inspection.product_guess?`Creo que veo: ${inspection.product_guess}.`:'',visible?`Visible: ${visible}.`:'',inspection.notes||''].filter(Boolean).join(' ');if(inspection.ready){$('#studioQuestion').hidden=true;$('#studioGenerate').disabled=false;status('La IA tiene suficiente información. Puedes generar o agregar una indicación opcional.');}else{$('#studioQuestion').hidden=false;$('#studioQuestionTitle').textContent='La IA necesita confirmar algo contigo';$('#studioQuestionText').textContent=inspection.question||'Confirma la información que no pueda deducirse con seguridad.';$('#studioAnswer').placeholder=inspection.suggested_answer_hint||'Escribe aquí la información confirmada…';$('#studioGenerate').disabled=true;status('Responde la pregunta y luego genera.');}}catch(e){status(e.message+(e.detail?` — ${e.detail}`:''));}finally{b.disabled=false;view.classList.remove('studio-loading');}}
  $('#studioAnswer').addEventListener('input',()=>{if(inspection&&!inspection.ready)$('#studioGenerate').disabled=!$('#studioAnswer').value.trim();});
  async function generate(){if(!file)return;const ans=$('#studioAnswer').value.trim();if(inspection&&!inspection.ready&&!ans){status('Responde primero la pregunta de la IA.');return;}if(selected.needs==='ingredients'&&!ans){status('Confirma los ingredientes antes de generar.');return;}const b=$('#studioGenerate');b.disabled=true;view.classList.add('studio-loading');status(`Generando /${selected.id} con GPT-Image-2… puede tardar un poco.`);try{const d=await postForm('generate',file,{brand_id:$('#studioBrand').value,frame:selected.id,answer:ans,idea:$('#studioIdea').value,inspection:inspection?JSON.stringify(inspection):''});result=d;$('#studioGeneratedPreview').src=d.media_url;$('#studioResult').classList.add('active');status('Imagen lista. Puedes regenerarla o enviarla al Publicador.');$('#studioResult').scrollIntoView({behavior:'smooth',block:'center'});}catch(e){status(e.message+(e.detail?` — ${e.detail}`:''));}finally{b.disabled=false;view.classList.remove('studio-loading');}}
  $('#studioAnalyze').onclick=inspect;$('#studioGenerate').onclick=generate;$('#studioRegenerate').onclick=generate;
  $('#studioUse').onclick=()=>{if(!result)return;window.dispatchEvent(new CustomEvent('laberinto:studio-media',{detail:{media_url:result.media_url,media_path:result.media_path,brand_id:$('#studioBrand').value,frame:selected.id}}));document.querySelector('#tabPublicador')?.click();status('Enviada al Publicador.');};
  $('#studioBrand').addEventListener('change',()=>{inspection=null;$('#studioQuestion').hidden=true;resetResult();if(file)status('Marca cambiada. Vuelve a analizar para aplicar su identidad visual.');});
 }
 boot();
})();