const BRANDS={sushi:{name:'Adrià Sushi'},sangucheria:{name:'Sanguchería Adrià'},pet:{name:'Adrià PET'},laberinto:{name:'Laberinto Digital'}};
const DEFAULT_POSTS=[];
const DEFAULT_LIBRARY=[];
let state=loadState();
function todayISO(){return new Date().toLocaleDateString('sv-SE');}
function loadState(){try{const parsed=JSON.parse(localStorage.getItem('laberinto-publicador-v1'));if(parsed?.posts&&parsed?.library){const legacy=['El sushi del barrio','Antojo de fuente de soda','Snack natural de la semana','Reutilizar publicación histórica'];parsed.posts=parsed.posts.filter(p=>!legacy.includes(p.title));return parsed;}}catch(e){}return{posts:[],library:[]};}
function saveState(){localStorage.setItem('laberinto-publicador-v1',JSON.stringify(state));render();}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function statusLabel(s){return({scheduled:'Programada',published:'Publicada',failed:'Falló',cancelled:'Cancelada'})[s]||s;}
function formatDate(date){try{return new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short'}).format(new Date(date+'T12:00:00'));}catch{return date;}}
function render(){renderFilters();renderStats();renderPosts();renderLibrary();}
function renderFilters(){const options=`<option value="all">Todas las marcas</option>`+Object.entries(BRANDS).map(([k,b])=>`<option value="${k}">${b.name}</option>`).join('');const bf=document.querySelector('#brandFilter'),pb=document.querySelector('#postBrand');if(bf&&!bf.dataset.ready){bf.innerHTML=options;bf.dataset.ready='1';}if(pb&&!pb.dataset.ready){pb.innerHTML=Object.entries(BRANDS).map(([k,b])=>`<option value="${k}">${b.name}</option>`).join('');pb.dataset.ready='1';}}
function renderStats(){const today=todayISO();const tc=document.querySelector('#todayCount'),sc=document.querySelector('#scheduledCount'),lc=document.querySelector('#libraryCount');if(tc)tc.textContent=state.posts.filter(p=>p.date===today&&p.status==='scheduled').length;if(sc)sc.textContent=state.posts.filter(p=>p.status==='scheduled').length;if(lc)lc.textContent=state.library.length;}
function renderPosts(){const brand=document.querySelector('#brandFilter')?.value||'all',list=state.posts.filter(p=>p.status==='scheduled'&&(brand==='all'||p.brand===brand)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)),el=document.querySelector('#postList');if(!el)return;el.innerHTML=list.length?list.map(p=>`<article class="post-card" data-id="${p.id}"><div><div class="post-meta"><span>${esc(BRANDS[p.brand]?.name||p.brand)}</span><span>${formatDate(p.date)} · ${esc(p.time)}</span></div><div class="post-title">${esc(p.title)}</div><div class="post-copy">${esc(p.copy||'')}</div></div><span class="badge scheduled">Programada</span></article>`).join(''):`<div class="empty minimal-empty"><strong>No hay contenido programado</strong><span>Cuando apruebes y programes una publicación, aparecerá aquí.</span></div>`;el.querySelectorAll('.post-card').forEach(card=>card.addEventListener('click',()=>openEditor(card.dataset.id)));}
function renderLibrary(){const el=document.querySelector('#libraryList');if(!el)return;const list=[...state.library].sort((a,b)=>((b.likes+b.comments)-(a.likes+a.comments))).slice(0,8);el.innerHTML=list.length?list.map(i=>`<article class="library-card"><div class="library-meta"><span>${esc(BRANDS[i.brand]?.name||i.brand)}</span><span>${formatDate(i.date)}</span></div><div class="post-copy">${esc(i.text||'Publicación histórica')}</div></article>`).join(''):`<div class="empty">La biblioteca histórica se administra desde Configuración.</div>`;}
function openEditor(id){const dialog=document.querySelector('#postDialog'),p=state.posts.find(x=>x.id===id);if(!dialog)return;document.querySelector('#dialogTitle').textContent=p?'Editar publicación':'Nueva publicación';document.querySelector('#postId').value=p?.id||'';document.querySelector('#postBrand').value=p?.brand||'sushi';document.querySelector('#postStatus').value=p?.status||'scheduled';document.querySelector('#postDate').value=p?.date||todayISO();document.querySelector('#postTime').value=p?.time||'13:00';document.querySelector('#postTitle').value=p?.title||'';document.querySelector('#postCopy').value=p?.copy||'';document.querySelector('#postMedia').value=p?.media||'';document.querySelector('#deletePostBtn').classList.toggle('hidden',!p);dialog.showModal();}
function closeEditor(){document.querySelector('#postDialog')?.close();}
function parseCSV(text){const lines=text.replace(/\r/g,'').split('\n').filter(Boolean);if(lines.length<2)return[];const parseLine=line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++;}else q=!q;}else if(c===','&&!q){out.push(cur);cur='';}else cur+=c;}out.push(cur);return out;};const headers=parseLine(lines[0]).map(h=>h.trim().toLowerCase());return lines.slice(1).map(line=>{const cols=parseLine(line),o={};headers.forEach((h,i)=>o[h]=cols[i]??'');return o;});}
function normalizeBrand(v=''){const x=v.toLowerCase();if(x.includes('sang'))return'sangucheria';if(x.includes('pet'))return'pet';if(x.includes('laber'))return'laberinto';return'sushi';}
function bind(){document.querySelector('#newPostBtn')?.addEventListener('click',()=>openEditor());document.querySelector('#closeDialog')?.addEventListener('click',closeEditor);document.querySelector('#cancelBtn')?.addEventListener('click',closeEditor);document.querySelector('#brandFilter')?.addEventListener('change',renderPosts);document.querySelector('#postForm')?.addEventListener('submit',e=>{e.preventDefault();const id=document.querySelector('#postId').value,data={id:id||crypto.randomUUID(),brand:document.querySelector('#postBrand').value,status:'scheduled',date:document.querySelector('#postDate').value,time:document.querySelector('#postTime').value,title:document.querySelector('#postTitle').value.trim(),copy:document.querySelector('#postCopy').value.trim(),media:document.querySelector('#postMedia').value.trim()};const idx=state.posts.findIndex(p=>p.id===id);if(idx>=0)state.posts[idx]=data;else state.posts.push(data);saveState();closeEditor();});document.querySelector('#deletePostBtn')?.addEventListener('click',()=>{const id=document.querySelector('#postId').value;if(!id)return;state.posts=state.posts.filter(p=>p.id!==id);saveState();closeEditor();});document.querySelector('#historyImport')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;const rows=parseCSV(await file.text()),imported=rows.map(r=>({id:crypto.randomUUID(),date:r.fecha||r.date||todayISO(),brand:normalizeBrand(r.marca||r.brand||''),text:r.texto||r.caption||r.text||'',url:r.url||r.link||'',likes:Number(r.likes||r.me_gusta||0)||0,comments:Number(r.comentarios||r.comments||0)||0}));state.library=[...imported,...state.library];saveState();e.target.value='';});document.querySelector('#exportBtn')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`laberinto-publicador-${todayISO()}.json`;a.click();URL.revokeObjectURL(a.href);});document.querySelector('#importBackup')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const x=JSON.parse(await file.text());if(Array.isArray(x.posts)&&Array.isArray(x.library)){state=x;saveState();}}catch{alert('El respaldo no es válido.');}e.target.value='';});}
render();bind();