(() => {
  const API='https://ufsxdlmnjuaymdszyjue.supabase.co/functions/v1/brand-settings-api';
  const PIN_KEY='laberinto_session_pin';
  const brands={'adria-sushi':'Adrià Sushi','adria-sangucheria':'Sanguchería Adrià','pet':'Adrià PET','chef-rafael':'Chef Rafael','laberinto-digital':'Laberinto Digital'};
  const getPin=()=>sessionStorage.getItem(PIN_KEY)||'';
  const call=async(body)=>{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,pin:getPin()})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Error de conexión');return d;};
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const css=document.createElement('style');css.textContent=`.brand-manual{display:grid;gap:16px}.brand-manual-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.brand-manual-head select{min-width:240px}.manual-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.manual-grid label{display:grid;gap:6px;font-weight:750}.manual-grid textarea{min-height:130px;width:100%;resize:vertical}.manual-grid .wide{grid-column:1/-1}.manual-help{font-size:.8rem;color:#777;font-weight:400;line-height:1.45}.manual-status{font-size:.88rem;color:#666}.manual-status.ok{color:#287245}.manual-status.error{color:#a33232}.manual-summary{border-top:1px solid #ece9e3;padding-top:14px;display:grid;gap:8px;color:#5f574d;font-size:.9rem;line-height:1.5}.manual-summary h4{margin:0;color:#171717}.manual-actions{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}@media(max-width:760px){.manual-grid{grid-template-columns:1fr}.manual-grid .wide{grid-column:auto}}`;document.head.appendChild(css);
  function boot(){const settings=document.querySelector('#settingsView');if(!settings)return setTimeout(boot,150);const old=[...settings.querySelectorAll('.settings-card')].find(x=>x.querySelector('.eyebrow')?.textContent?.trim()==='VOZ DE MARCA');if(!old)return setTimeout(boot,150);const card=document.createElement('article');card.className='settings-card settings-full';card.innerHTML=`<span class="eyebrow">MANUAL DE MARCA</span><div class="brand-manual"><div class="brand-manual-head"><div><h3>Cómo piensa, habla y se comporta cada marca</h3><p class="helper">Este manual alimenta directamente a la IA cuando analiza imágenes y escribe contenido.</p></div><select id="manualBrand">${Object.entries(brands).map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select></div><div class="manual-grid"><label>Audiencia<textarea id="manualAudience"></textarea><span class="manual-help">A quién hablamos, qué busca y qué valora.</span></label><label>Objetivo<textarea id="manualObjective"></textarea><span class="manual-help">Qué debe conseguir el contenido para esta marca.</span></label><label class="wide">Identidad<textarea id="manualIdentity"></textarea><span class="manual-help">Qué es la marca, de dónde viene y qué significa.</span></label><label>Personalidad<textarea id="manualPersonality"></textarea><span class="manual-help">Cómo se comportaría la marca si fuera una persona.</span></label><label>Cómo hablamos<textarea id="manualSpeak"></textarea><span class="manual-help">Lenguaje, ritmo, cercanía, vocabulario y tono.</span></label><label>Cómo NO hablamos<textarea id="manualNotSpeak"></textarea><span class="manual-help">Frases, tonos y hábitos que hacen perder autenticidad.</span></label><label>Pilares editoriales<textarea id="manualPillars"></textarea><span class="manual-help">Temas que deben mantener el contenido variado y coherente.</span></label><label>CTA<textarea id="manualCTA"></textarea><span class="manual-help">Cómo invitamos a comprar, visitar, conversar o guardar.</span></label><label class="wide">Datos que la IA nunca puede inventar<textarea id="manualNever"></textarea><span class="manual-help">Precios, promociones, ingredientes, horarios y cualquier otro dato que requiere confirmación.</span></label></div><div class="manual-actions"><span id="manualStatus" class="manual-status">Cargando…</span><button id="manualSave" class="btn primary" type="button">Guardar manual de marca</button></div><div id="manualSummary" class="manual-summary"></div></div>`;old.replaceWith(card);
    let profiles={};
    const ids={audience:'#manualAudience',objective:'#manualObjective',identity:'#manualIdentity',personality:'#manualPersonality',how_we_speak:'#manualSpeak',how_not_we_speak:'#manualNotSpeak',editorial_pillars:'#manualPillars',cta:'#manualCTA',never_invent:'#manualNever'};
    function fill(){const id=document.querySelector('#manualBrand').value,v=profiles[id]||{};document.querySelector('#manualAudience').value=v.audience||'';document.querySelector('#manualObjective').value=v.objective||'';document.querySelector('#manualIdentity').value=v.identity||'';document.querySelector('#manualPersonality').value=v.personality||'';document.querySelector('#manualSpeak').value=v.how_we_speak||v.voice||'';document.querySelector('#manualNotSpeak').value=v.how_not_we_speak||'';document.querySelector('#manualPillars').value=v.editorial_pillars||'';document.querySelector('#manualCTA').value=v.cta||'';document.querySelector('#manualNever').value=v.never_invent||v.guardrails||'';summary();}
    function summary(){const name=brands[document.querySelector('#manualBrand').value],identity=document.querySelector('#manualIdentity').value.trim(),personality=document.querySelector('#manualPersonality').value.trim(),pillars=document.querySelector('#manualPillars').value.trim();document.querySelector('#manualSummary').innerHTML=`<h4>${esc(name)}</h4>${identity?`<div><strong>Es:</strong> ${esc(identity)}</div>`:''}${personality?`<div><strong>Se siente:</strong> ${esc(personality)}</div>`:''}${pillars?`<div><strong>Debe hablar de:</strong> ${esc(pillars)}</div>`:''}`;}
    async function load(){const s=document.querySelector('#manualStatus');try{const d=await call({action:'list'});profiles=Object.fromEntries((d.items||[]).map(x=>[x.brand_id,x]));fill();s.textContent='Manual cargado desde el servidor.';s.className='manual-status ok';}catch(e){s.textContent=e.message;s.className='manual-status error';}}
    async function save(){const id=document.querySelector('#manualBrand').value,s=document.querySelector('#manualStatus'),btn=document.querySelector('#manualSave'),body={action:'save',brand_id:id};for(const [k,sel] of Object.entries(ids))body[k]=document.querySelector(sel).value;btn.disabled=true;s.textContent='Guardando…';s.className='manual-status';try{const d=await call(body);profiles[id]=d.item;s.textContent='Guardado. La IA usará este manual desde la próxima publicación.';s.className='manual-status ok';fill();}catch(e){s.textContent=e.message;s.className='manual-status error';}finally{btn.disabled=false;}}
    document.querySelector('#manualBrand').addEventListener('change',fill);Object.values(ids).forEach(sel=>document.querySelector(sel).addEventListener('input',summary));document.querySelector('#manualSave').addEventListener('click',save);load();
  }
  boot();
})();