(() => {
  const DRIVE_API='https://ufsxdlmnjuaymdszyjue.supabase.co/functions/v1/drive-library-api';
  const AI_API='https://ufsxdlmnjuaymdszyjue.supabase.co/functions/v1/laberinto-api';
  const PIN_KEY='laberinto_session_pin';
  let items=[], selected=null, analysis=null;
  const getPin=()=>sessionStorage.getItem(PIN_KEY)||'';
  const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

  const css=document.createElement('style');
  css.textContent=`
  .drive-lib{margin:18px 0}.drive-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.drive-status{color:#6b6256;font-size:.9rem}
  .drive-gallery{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:12px;margin-top:14px}.drive-card{border:1px solid #e7dfd2;border-radius:14px;overflow:hidden;background:#fff;display:grid}.drive-card img{width:100%;aspect-ratio:1/1;object-fit:cover;background:#f4efe7}.drive-card-body{padding:10px;display:grid;gap:6px}.drive-card strong{font-size:.94rem;line-height:1.2}.drive-card small{color:#786f64}.drive-card .btn{width:100%}.drive-empty{padding:22px;border:1px dashed #d9cdbc;border-radius:14px;text-align:center;color:#756b5d}.drive-rescue{background:#f5edff;border:1px solid #dac4fa;border-radius:12px;padding:10px 12px}
  #driveEditor{width:min(760px,94vw);border:0;border-radius:18px;padding:0;box-shadow:0 30px 90px rgba(0,0,0,.3)}#driveEditor::backdrop{background:rgba(17,24,39,.7)}.drive-editor-wrap{padding:20px;display:grid;gap:14px}.drive-editor-grid{display:grid;grid-template-columns:minmax(180px,.7fr) minmax(280px,1.3fr);gap:16px}.drive-editor-grid img{width:100%;max-height:390px;object-fit:contain;border-radius:14px;background:#f7f3ec}.drive-fields{display:grid;gap:10px}.drive-fields label{display:grid;gap:5px;font-weight:650}.drive-fields textarea{min-height:170px;width:100%}.drive-editor-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap}.drive-editor-status{font-size:.9rem;color:#655c50}
  @media(max-width:700px){.drive-gallery{grid-template-columns:repeat(2,minmax(0,1fr))}.drive-editor-grid{grid-template-columns:1fr}#driveEditor{width:96vw}.drive-editor-wrap{padding:14px}}
  `;document.head.appendChild(css);

  const panel=document.createElement('section');panel.className='panel drive-lib';panel.innerHTML=`
    <div class="panel-heading"><div><span class="eyebrow">BIBLIOTECA INTELIGENTE</span><h2>Fotos Adrià · Google Drive</h2></div><span id="driveBadge" class="ai-badge warn">Comprobando Drive</span></div>
    <p class="helper">Copia fotos de la carpeta compartida a Laberinto para que la IA pueda analizarlas y Meta pueda publicarlas automáticamente.</p>
    <div class="drive-actions"><button id="driveConnect" class="btn secondary" type="button">Autorizar Drive</button><button id="driveSync" class="btn primary" type="button">Importar 20 fotos</button><button id="driveRescue" class="btn secondary" type="button">Sugerir Rescate</button><select id="driveCategory"><option value="">Todas las categorías</option></select><button id="driveRefresh" class="btn ghost" type="button">Actualizar</button></div>
    <p id="driveStatus" class="drive-status">Preparando biblioteca…</p><div id="driveGallery" class="drive-gallery"></div>`;
  const aiPanel=document.querySelector('.ai-publisher'); if(aiPanel) aiPanel.insertAdjacentElement('afterend',panel); else document.querySelector('main.shell,main')?.prepend(panel);

  const dialog=document.createElement('dialog');dialog.id='driveEditor';dialog.innerHTML=`<div class="drive-editor-wrap"><div class="panel-heading"><div><span class="eyebrow">REUTILIZAR CON IA</span><h2 id="driveEditorHeading">Crear publicación</h2></div><button id="driveEditorClose" class="icon-btn" type="button">×</button></div><div class="drive-editor-grid"><img id="driveEditorImage" alt="Foto histórica"><div class="drive-fields"><label>Enfoque opcional<input id="driveContext" type="text" placeholder="Ej: recordar este clásico del barrio"></label><button id="driveAnalyze" class="btn secondary" type="button">Volver a analizar</button><label>Título<input id="driveTitle" type="text" maxlength="120"></label><label>Texto listo para publicar<textarea id="driveCaption"></textarea></label><label>Fecha y hora<input id="driveSchedule" type="datetime-local"></label><div id="driveEditorStatus" class="drive-editor-status"></div></div></div><div class="drive-editor-actions"><button id="driveCancel" class="btn secondary" type="button">Cancelar</button><button id="driveScheduleBtn" class="btn primary" type="button">Programar publicación</button></div></div>`;document.body.appendChild(dialog);

  const $=s=>document.querySelector(s);const setStatus=t=>{$('#driveStatus').textContent=t};const editorStatus=t=>{$('#driveEditorStatus').textContent=t};
  async function call(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,pin:getPin()})});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||'Error de conexión');e.detail=d.detail;throw e;}return d;}
  function tomorrow(){const d=new Date();d.setDate(d.getDate()+1);d.setHours(13,0,0,0);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
  async function status(){try{const d=await call(DRIVE_API,{action:'status'});const b=$('#driveBadge');b.textContent=d.drive_ready?`Drive listo · ${d.imported_count}`:'Drive requiere permiso';b.className='ai-badge '+(d.drive_ready?'ok':'warn');$('#driveSync').disabled=!d.drive_ready;setStatus(d.drive_ready?`${d.imported_count} fotos ya están copiadas en la biblioteca de Laberinto.`:'Autoriza Google Drive una vez para comenzar a importar.');return d;}catch(e){setStatus(e.message);return null}}
  async function load(category=''){try{const d=await call(DRIVE_API,{action:'list',category});items=d.items||[];render();buildCategories();}catch(e){setStatus(e.message)}}
  function buildCategories(){const sel=$('#driveCategory'),current=sel.value;const cats=[...new Set(items.map(x=>x.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));if(!current){sel.innerHTML='<option value="">Todas las categorías</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');}}
  function render(){const root=$('#driveGallery');if(!items.length){root.innerHTML='<div class="drive-empty">Todavía no hay fotos importadas. Pulsa <strong>Importar 20 fotos</strong>.</div>';return;}root.innerHTML=items.map(x=>`<article class="drive-card"><img loading="lazy" src="${esc(x.media_url)}" alt="${esc(x.title)}"><div class="drive-card-body"><strong>${esc(x.title)}</strong><small>${esc(x.category||'Sin categoría')}${x.source_date?' · '+new Date(x.source_date).getFullYear():''}</small><button class="btn secondary drive-use" data-id="${x.id}" type="button">Crear con IA</button></div></article>`).join('');root.querySelectorAll('.drive-use').forEach(b=>b.addEventListener('click',()=>openEditor(items.find(x=>x.id===b.dataset.id))));}
  async function sync(){if(!getPin()){setStatus('Ingresa primero al Publicador con tu código de acceso.');return;}$('#driveSync').disabled=true;setStatus('Importando desde Drive y copiando fotos a Laberinto… puede tardar un poco.');try{const d=await call(DRIVE_API,{action:'sync',limit:20});setStatus(`Importación terminada: ${d.imported} nuevas · ${d.exists} ya existían · ${d.skipped} omitidas.${d.errors?.length?' '+d.errors.length+' con error.':''}`);await status();await load();}catch(e){setStatus(e.message==='GOOGLE_NOT_CONNECTED'?'Debes autorizar Google Drive nuevamente.':e.message);}finally{$('#driveSync').disabled=false}}
  async function rescue(){try{const d=await call(DRIVE_API,{action:'rescue'});if(!d.item){setStatus('Primero importa fotos para activar Rescate.');return;}setStatus(`Rescate encontró: ${d.item.title} · ${d.item.category}`);openEditor(d.item,true);}catch(e){setStatus(e.message)}}
  function openEditor(item,isRescue=false){if(!item)return;selected=item;analysis=null;$('#driveEditorHeading').textContent=isRescue?'Sugerencia Rescate 13:00':item.title;$('#driveEditorImage').src=item.media_url;$('#driveContext').value=isRescue?`Rescate 13:00: reutilizar una foto histórica de ${item.category||'Adrià'} con un enfoque actual y cercano.`:`Reutilizar material histórico de ${item.category||'Adrià'} con un enfoque actual.`;$('#driveTitle').value=item.title||'';$('#driveCaption').value='';$('#driveSchedule').value=tomorrow();editorStatus('Analizando la foto con IA…');dialog.showModal();analyze();}
  async function analyze(){if(!selected)return;$('#driveAnalyze').disabled=true;editorStatus('Analizando imagen y preparando un copy nuevo…');try{const d=await call(AI_API,{action:'analyze',brand_id:'adria-sushi',media_url:selected.media_url,context:$('#driveContext').value});analysis=d.analysis||{};$('#driveTitle').value=analysis.title||selected.title||'';const tags=Array.isArray(analysis.hashtags)&&analysis.hashtags.length?'\n\n'+analysis.hashtags.join(' '):'';$('#driveCaption').value=(analysis.caption||'')+tags;const w=Array.isArray(analysis.warnings)?analysis.warnings.filter(Boolean):[];editorStatus(w.length?'Revisar: '+w.join(' · '):'Copy nuevo listo. Puedes editarlo antes de programar.');}catch(e){editorStatus((e.message||'No se pudo analizar')+(e.detail?' · '+e.detail:''));}finally{$('#driveAnalyze').disabled=false}}
  async function schedule(){if(!selected)return;const caption=$('#driveCaption').value.trim(),dt=$('#driveSchedule').value;if(!caption||!dt){editorStatus('Falta texto o fecha/hora.');return;}$('#driveScheduleBtn').disabled=true;editorStatus('Programando…');try{await call(AI_API,{action:'schedule',brand_id:'adria-sushi',title:$('#driveTitle').value,caption,media_url:selected.media_url,media_path:selected.media_path,ai_analysis:analysis||{},scheduled_at:new Date(dt).toISOString()});await call(DRIVE_API,{action:'mark_used',id:selected.id}).catch(()=>{});editorStatus('Publicación programada.');document.querySelector('#aiRefreshQueue')?.click();setTimeout(()=>dialog.close(),600);await load($('#driveCategory').value);}catch(e){editorStatus((e.message||'No se pudo programar')+(e.detail?' · '+e.detail:''));}finally{$('#driveScheduleBtn').disabled=false}}
  $('#driveConnect').addEventListener('click',()=>document.querySelector('#googleConnectButton')?.click());$('#driveSync').addEventListener('click',sync);$('#driveRescue').addEventListener('click',rescue);$('#driveRefresh').addEventListener('click',async()=>{await status();await load($('#driveCategory').value)});$('#driveCategory').addEventListener('change',()=>load($('#driveCategory').value));$('#driveAnalyze').addEventListener('click',analyze);$('#driveScheduleBtn').addEventListener('click',schedule);$('#driveEditorClose').addEventListener('click',()=>dialog.close());$('#driveCancel').addEventListener('click',()=>dialog.close());
  setTimeout(async()=>{const s=await status();if(s?.drive_ready)await load();},500);
})();
