(()=>{
const API='https://ufsxdlmnjuaymdszyjue.supabase.co/functions/v1/laberinto-api',PIN='laberinto_session_pin';
const brands={'adria-sushi':'Adrià Sushi','adria-sangucheria':'Sanguchería Adrià','pet':'Adrià PET','chef-rafael':'Chef Rafael','laberinto-digital':'Laberinto Digital'};
let brand='adria-sushi',selected=null,imported=null,analysis=null;const seen={};
const S=()=>seen[brand]||(seen[brand]=new Set()),pin=()=>sessionStorage.getItem(PIN)||'',esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function call(body){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,pin:pin()})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Error de conexión');return d}
const img=x=>x.media_url||x.thumbnail_url||'',shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function batch(items){const now=Date.now(),day=864e5,c=items.filter(x=>['IMAGE','CAROUSEL_ALBUM'].includes(x.media_type)&&new Date(x.timestamp||0).getTime()<now-60*day&&!S().has(String(x.id))&&img(x)),r=c.filter(x=>new Date(x.timestamp).getTime()>=now-365*day),m=c.filter(x=>{const t=new Date(x.timestamp).getTime();return t<now-365*day&&t>=now-3*365*day}),o=c.filter(x=>new Date(x.timestamp).getTime()<now-3*365*day),out=[];const take=(p,n)=>shuffle(p).some(x=>{if(n<=0||out.length>=4)return true;if(!out.some(y=>String(y.id)===String(x.id))){out.push(x);n--}return false});take(r,2);take(m,1);take(o,1);take(c,4-out.length);return shuffle(out).slice(0,4)}
const css=document.createElement('style');css.textContent='.ig-rescue{margin:18px 0}.ig-rescue-actions,.ig-card-actions{display:flex;gap:8px;flex-wrap:wrap}.ig-rescue-actions select{min-width:220px}.ig-rescue-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:14px}.ig-rescue-card{border:1px solid #e7dfd2;border-radius:14px;overflow:hidden;background:#fff}.ig-rescue-card>img{width:100%;aspect-ratio:1;object-fit:cover}.ig-rescue-body{padding:10px;display:grid;gap:7px}.ig-rescue-body p{margin:0;font-size:.86rem;color:#655c50;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.ig-rescue-meta{font-size:.78rem;color:#7a7065}.ig-card-actions .btn{flex:1 1 100%}.ig-studio-btn{background:#f7f2ea!important}.ig-rescue-empty{grid-column:1/-1;padding:22px;text-align:center}#igRescueEditor{width:min(780px,94vw);border:0;border-radius:18px;padding:0}.ig-rescue-editor{padding:20px;display:grid;gap:14px}.ig-rescue-editor-grid{display:grid;grid-template-columns:minmax(200px,.8fr) minmax(300px,1.2fr);gap:16px}.ig-rescue-editor-grid img{width:100%;max-height:410px;object-fit:contain}.ig-rescue-fields{display:grid;gap:10px}.ig-rescue-fields textarea{min-height:190px}.ig-rescue-editor-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap}@media(max-width:850px){.ig-rescue-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.ig-rescue-editor-grid{grid-template-columns:1fr}}';document.head.appendChild(css);
const panel=document.createElement('section');panel.className='panel ig-rescue';panel.innerHTML=`<div class="panel-heading"><div><span class="eyebrow">RESCATE DESDE INSTAGRAM</span><h2>Encuentra algo bueno para volver a publicar</h2></div><span class="ai-badge ok">4 variados</span></div><p class="helper">Cada tanda mezcla contenido reciente y antiguo al azar. Ahora también puedes llevar cualquier rescate directo a Estudio IA.</p><div class="ig-rescue-actions"><select id="igRescueBrand">${Object.entries(brands).map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select><button id="igRescueBtn" class="btn primary">Buscar 4 rescates</button></div><p id="igRescueStatus" class="drive-status">Selecciona una cuenta y pide tus primeras 4 opciones.</p><div id="igRescueGrid" class="ig-rescue-grid"></div>`;(document.querySelector('.ai-publisher')||document.querySelector('main.shell,main'))?.insertAdjacentElement(document.querySelector('.ai-publisher')?'afterend':'afterbegin',panel);
const dialog=document.createElement('dialog');dialog.id='igRescueEditor';dialog.innerHTML=`<div class="ig-rescue-editor"><div class="panel-heading"><div><span class="eyebrow">RESCATE CON IA</span><h2 id="igRescueHeading">Preparar publicación</h2></div><button id="igRescueClose" class="icon-btn">×</button></div><div class="ig-rescue-editor-grid"><img id="igRescueImage"><div class="ig-rescue-fields"><label>Enfoque actual<input id="igRescueContext"></label><button id="igRescueAnalyze" class="btn secondary">Volver a analizar</button><label>Título<input id="igRescueTitle"></label><label>Texto listo para publicar<textarea id="igRescueCaption"></textarea></label><label>Fecha y hora<input id="igRescueSchedule" type="datetime-local"></label><div id="igRescueEditorStatus"></div></div></div><div class="ig-rescue-editor-actions"><button id="igRescueCancel" class="btn secondary">Cancelar</button><button id="igRescueScheduleBtn" class="btn primary">Programar publicación</button></div></div>`;document.body.appendChild(dialog);
const $=s=>document.querySelector(s),status=t=>$('#igRescueStatus').textContent=t,est=t=>$('#igRescueEditorStatus').textContent=t,tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);d.setHours(13,0,0,0);return new Date(d-d.getTimezoneOffset()*6e4).toISOString().slice(0,16)};
function render(items){const root=$('#igRescueGrid');if(!items.length){root.innerHTML='<div class="ig-rescue-empty">No encontré más publicaciones antiguas compatibles.</div>';return}root.innerHTML=items.map((x,i)=>`<article class="ig-rescue-card"><img src="${esc(img(x))}"><div class="ig-rescue-body"><strong>Opción ${i+1}</strong><div class="ig-rescue-meta">${x.timestamp?new Date(x.timestamp).toLocaleDateString('es-CL'):''}</div><p>${esc(x.caption||'Publicación histórica')}</p><div class="ig-card-actions"><button class="btn secondary ig-rescue-use" data-id="${esc(x.id)}">Usar esta</button><button class="btn secondary ig-studio-btn" data-id="${esc(x.id)}">Mejorar con Estudio IA</button></div></div></article>`).join('');root.querySelectorAll('.ig-rescue-use').forEach(b=>b.onclick=()=>openEditor(items.find(x=>String(x.id)===b.dataset.id)));root.querySelectorAll('.ig-studio-btn').forEach(b=>b.onclick=()=>toStudio(items.find(x=>String(x.id)===b.dataset.id),b))}
async function rescue(){brand=$('#igRescueBrand').value;$('#igRescueBtn').disabled=true;status('Buscando 4 opciones variadas…');try{const d=await call({action:'instagram_history',brand_id:brand,max_items:1200}),a=batch(d.items||[]);a.forEach(x=>S().add(String(x.id)));render(a);$('#igRescueBtn').textContent=a.length?'Mostrar 4 más':'Volver a empezar';status(a.length?`4 opciones de ${brands[brand]}. Puedes reutilizarlas tal cual o recrearlas en Estudio IA.`:'No quedan opciones nuevas en esta ronda.');if(!a.length)S().clear()}catch(e){status(e.message)}finally{$('#igRescueBtn').disabled=false}}
async function toStudio(item,b){if(!item)return;b.disabled=true;b.textContent='Preparando…';try{const d=await call({action:'instagram_rescue_import',brand_id:brand,media_id:item.id,media_url:img(item)});window.dispatchEvent(new CustomEvent('laberinto:rescue-to-studio',{detail:{media_url:d.media_url,media_path:d.media_path,brand_id:brand,original_media_id:item.id,original_timestamp:item.timestamp||null,original_caption:item.caption||''}}));document.querySelector('#tabStudio')?.click()}catch(e){status('No se pudo enviar al Estudio IA: '+e.message)}finally{b.disabled=false;b.textContent='Mejorar con Estudio IA'}}
async function openEditor(item){selected=item;imported=null;analysis=null;$('#igRescueHeading').textContent=`Rescatar en ${brands[brand]}`;$('#igRescueImage').src=img(item);$('#igRescueContext').value='Reutilizar esta publicación histórica con un enfoque actual y natural.';$('#igRescueCaption').value=item.caption||'';$('#igRescueSchedule').value=tomorrow();dialog.showModal();est('Preparando…');try{imported=await call({action:'instagram_rescue_import',brand_id:brand,media_id:item.id,media_url:img(item)});$('#igRescueImage').src=imported.media_url;await analyze()}catch(e){est(e.message)}}
async function analyze(){if(!selected||!imported)return;est('Creando una versión actual…');try{const d=await call({action:'analyze',brand_id:brand,media_url:imported.media_url,context:`${$('#igRescueContext').value} Texto original: ${(selected.caption||'').slice(0,1200)}`});analysis=d.analysis||{};$('#igRescueTitle').value=analysis.title||'Rescate del archivo';$('#igRescueCaption').value=(analysis.caption||'')+(Array.isArray(analysis.hashtags)&&analysis.hashtags.length?'\n\n'+analysis.hashtags.join(' '):'');est('Versión nueva lista.')}catch(e){est(e.message)}}
async function schedule(){if(!imported)return;try{await call({action:'schedule',brand_id:brand,title:$('#igRescueTitle').value,caption:$('#igRescueCaption').value,media_url:imported.media_url,media_path:imported.media_path,ai_analysis:{...(analysis||{}),rescue_source:'instagram',original_media_id:selected.id},scheduled_at:new Date($('#igRescueSchedule').value).toISOString()});est('Publicación programada.');setTimeout(()=>dialog.close(),700)}catch(e){est(e.message)}}
$('#igRescueBrand').onchange=()=>{brand=$('#igRescueBrand').value;$('#igRescueGrid').innerHTML='';status(`Cuenta seleccionada: ${brands[brand]}.`)};$('#igRescueBtn').onclick=rescue;$('#igRescueAnalyze').onclick=analyze;$('#igRescueScheduleBtn').onclick=schedule;$('#igRescueClose').onclick=$('#igRescueCancel').onclick=()=>dialog.close();
})();