(() => {
  const API='https://ufsxdlmnjuaymdszyjue.supabase.co/functions/v1/laberinto-api';
  const PIN_KEY='laberinto_session_pin';
  const brands={
    'adria-sushi':'Adrià Sushi',
    'adria-sangucheria':'Sanguchería Adrià',
    'pet':'Adrià PET',
    'chef-rafael':'Chef Rafael',
    'laberinto-digital':'Laberinto Digital'
  };
  let currentBrand='adria-sushi', selected=null, imported=null, analysis=null;
  const getPin=()=>sessionStorage.getItem(PIN_KEY)||'';
  const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const call=async body=>{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,pin:getPin()})});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||'Error de conexión');e.detail=d.detail||'';throw e;}return d;};
  const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);d.setHours(13,0,0,0);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};

  const css=document.createElement('style');css.textContent=`
    .ig-rescue{margin:18px 0}.ig-rescue-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.ig-rescue-actions select{min-width:220px}.ig-rescue-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:14px}.ig-rescue-card{border:1px solid #e7dfd2;border-radius:14px;overflow:hidden;background:#fff;display:grid}.ig-rescue-card img{width:100%;aspect-ratio:1/1;object-fit:cover;background:#f4efe7}.ig-rescue-body{padding:10px;display:grid;gap:7px}.ig-rescue-body p{margin:0;font-size:.86rem;line-height:1.35;color:#655c50;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.ig-rescue-meta{font-size:.78rem;color:#7a7065}.ig-rescue-card .btn{width:100%}.ig-rescue-empty{grid-column:1/-1;padding:22px;border:1px dashed #d9cdbc;border-radius:14px;text-align:center;color:#756b5d}
    #igRescueEditor{width:min(780px,94vw);border:0;border-radius:18px;padding:0;box-shadow:0 30px 90px rgba(0,0,0,.3)}#igRescueEditor::backdrop{background:rgba(17,24,39,.7)}.ig-rescue-editor{padding:20px;display:grid;gap:14px}.ig-rescue-editor-grid{display:grid;grid-template-columns:minmax(200px,.8fr) minmax(300px,1.2fr);gap:16px}.ig-rescue-editor-grid img{width:100%;max-height:410px;object-fit:contain;border-radius:14px;background:#f7f3ec}.ig-rescue-fields{display:grid;gap:10px}.ig-rescue-fields label{display:grid;gap:5px;font-weight:650}.ig-rescue-fields textarea{min-height:190px;width:100%}.ig-rescue-editor-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap}.ig-rescue-status{font-size:.9rem;color:#655c50}
    @media(max-width:850px){.ig-rescue-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.ig-rescue-grid{grid-template-columns:1fr 1fr}.ig-rescue-editor-grid{grid-template-columns:1fr}.ig-rescue-editor{padding:14px}}
  `;document.head.appendChild(css);

  const panel=document.createElement('section');panel.className='panel ig-rescue';panel.innerHTML=`
    <div class="panel-heading"><div><span class="eyebrow">RESCATE DESDE INSTAGRAM</span><h2>Recupera lo mejor de cada cuenta</h2></div><span id="igRescueBadge" class="ai-badge ok">4 opciones</span></div>
    <p class="helper">Elige primero la cuenta. Laberinto revisa su historial y muestra solo cuatro publicaciones antiguas con mejor potencial de rescate.</p>
    <div class="ig-rescue-actions"><select id="igRescueBrand" aria-label="Cuenta para rescatar">${Object.entries(brands).map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select><button id="igRescueBtn" class="btn primary" type="button">Buscar 4 rescates</button></div>
    <p id="igRescueStatus" class="drive-status">Selecciona una cuenta y pulsa Buscar 4 rescates.</p><div id="igRescueGrid" class="ig-rescue-grid"></div>`;
  const drivePanel=document.querySelector('.drive-lib');if(drivePanel)drivePanel.insertAdjacentElement('afterend',panel);else document.querySelector('main.shell,main')?.prepend(panel);

  const dialog=document.createElement('dialog');dialog.id='igRescueEditor';dialog.innerHTML=`<div class="ig-rescue-editor"><div class="panel-heading"><div><span class="eyebrow">RESCATE CON IA</span><h2 id="igRescueHeading">Preparar publicación</h2></div><button id="igRescueClose" class="icon-btn" type="button">×</button></div><div class="ig-rescue-editor-grid"><img id="igRescueImage" alt="Publicación histórica"><div class="ig-rescue-fields"><label>Enfoque actual<input id="igRescueContext" type="text" placeholder="Ej: traer este clásico de vuelta"></label><button id="igRescueAnalyze" class="btn secondary" type="button">Volver a analizar</button><label>Título<input id="igRescueTitle" type="text" maxlength="120"></label><label>Texto listo para publicar<textarea id="igRescueCaption"></textarea></label><label>Fecha y hora<input id="igRescueSchedule" type="datetime-local"></label><div id="igRescueEditorStatus" class="ig-rescue-status"></div></div></div><div class="ig-rescue-editor-actions"><button id="igRescueCancel" class="btn secondary" type="button">Cancelar</button><button id="igRescueScheduleBtn" class="btn primary" type="button">Programar publicación</button></div></div>`;document.body.appendChild(dialog);

  const $=s=>document.querySelector(s), status=t=>{$('#igRescueStatus').textContent=t}, editorStatus=t=>{$('#igRescueEditorStatus').textContent=t};
  function imageOf(x){return x.media_url||x.thumbnail_url||''}
  function render(items){const root=$('#igRescueGrid');if(!items.length){root.innerHTML='<div class="ig-rescue-empty">No encontré publicaciones antiguas compatibles para esta cuenta.</div>';return;}root.innerHTML=items.slice(0,4).map((x,i)=>{const date=x.timestamp?new Date(x.timestamp).toLocaleDateString('es-CL'):'';return `<article class="ig-rescue-card"><img loading="lazy" src="${esc(imageOf(x))}" alt="Rescate ${i+1}"><div class="ig-rescue-body"><strong>Opción ${i+1}</strong><div class="ig-rescue-meta">${esc(date)} · puntaje ${Number(x.rescue_score||0)}</div><p>${esc(x.caption||'Publicación histórica')}</p><button class="btn secondary ig-rescue-use" data-id="${esc(x.id)}" type="button">Usar esta</button></div></article>`}).join('');root.querySelectorAll('.ig-rescue-use').forEach(b=>b.addEventListener('click',()=>openEditor(items.find(x=>x.id===b.dataset.id))));}
  async function rescue(){if(!getPin()){status('Ingresa primero al Publicador con tu código de acceso.');return;}currentBrand=$('#igRescueBrand').value;$('#igRescueBtn').disabled=true;status(`Revisando el historial de ${brands[currentBrand]}…`);$('#igRescueGrid').innerHTML='';try{const d=await call({action:'instagram_rescue',brand_id:currentBrand,limit:4,max_items:1200});render(d.items||[]);status(`Revisé ${d.scanned||0} publicaciones de ${brands[currentBrand]} y elegí las 4 con mejor potencial.`);}catch(e){status((e.message||'No se pudo revisar Instagram')+(e.detail?' · '+e.detail:''));}finally{$('#igRescueBtn').disabled=false}}
  async function openEditor(item){if(!item)return;selected=item;imported=null;analysis=null;$('#igRescueHeading').textContent=`Rescatar en ${brands[currentBrand]}`;$('#igRescueImage').src=imageOf(item);$('#igRescueContext').value=`Reutilizar esta publicación histórica de ${brands[currentBrand]} con un enfoque actual, natural y sin copiar literalmente el texto antiguo.`;$('#igRescueTitle').value='';$('#igRescueCaption').value=item.caption||'';$('#igRescueSchedule').value=tomorrow();editorStatus('Copiando la imagen a Laberinto y preparando un texto nuevo con IA…');dialog.showModal();try{imported=await call({action:'instagram_rescue_import',brand_id:currentBrand,media_id:item.id,media_url:imageOf(item)});$('#igRescueImage').src=imported.media_url;await analyze();}catch(e){editorStatus(e.message||'No se pudo preparar esta publicación.');}}
  async function analyze(){if(!selected||!imported)return;$('#igRescueAnalyze').disabled=true;editorStatus('Analizando la imagen y creando una versión actual…');try{const context=`${$('#igRescueContext').value} Texto original de referencia: ${(selected.caption||'').slice(0,1200)}`;const d=await call({action:'analyze',brand_id:currentBrand,media_url:imported.media_url,context});analysis=d.analysis||{};$('#igRescueTitle').value=analysis.title||'Rescate del archivo';const tags=Array.isArray(analysis.hashtags)&&analysis.hashtags.length?'\n\n'+analysis.hashtags.join(' '):'';$('#igRescueCaption').value=(analysis.caption||'')+tags;editorStatus('Versión nueva lista. Puedes editarla antes de programar.');}catch(e){editorStatus((e.message||'No se pudo analizar')+(e.detail?' · '+e.detail:''));}finally{$('#igRescueAnalyze').disabled=false}}
  async function schedule(){if(!selected||!imported)return;const caption=$('#igRescueCaption').value.trim(),dt=$('#igRescueSchedule').value;if(!caption||!dt){editorStatus('Falta texto o fecha/hora.');return;}$('#igRescueScheduleBtn').disabled=true;editorStatus('Programando…');try{await call({action:'schedule',brand_id:currentBrand,title:$('#igRescueTitle').value,caption,media_url:imported.media_url,media_path:imported.media_path,ai_analysis:{...(analysis||{}),rescue_source:'instagram',original_media_id:selected.id,original_permalink:selected.permalink||null,original_timestamp:selected.timestamp||null},scheduled_at:new Date(dt).toISOString()});editorStatus('Publicación de rescate programada.');document.querySelector('#aiRefreshQueue')?.click();setTimeout(()=>dialog.close(),700);}catch(e){editorStatus((e.message||'No se pudo programar')+(e.detail?' · '+e.detail:''));}finally{$('#igRescueScheduleBtn').disabled=false}}
  $('#igRescueBrand').addEventListener('change',()=>{currentBrand=$('#igRescueBrand').value;$('#igRescueGrid').innerHTML='';status(`Cuenta seleccionada: ${brands[currentBrand]}. Pulsa Buscar 4 rescates.`)});$('#igRescueBtn').addEventListener('click',rescue);$('#igRescueAnalyze').addEventListener('click',analyze);$('#igRescueScheduleBtn').addEventListener('click',schedule);$('#igRescueClose').addEventListener('click',()=>dialog.close());$('#igRescueCancel').addEventListener('click',()=>dialog.close());
})();