(() => {
  const PIN_KEY='laberinto_session_pin';
  const TIME_API='https://ufsxdlmnjuaymdszyjue.supabase.co/functions/v1/posting-time-api';
  const brands={
    'adria-sushi':{name:'Adrià Sushi',sources:['adria.cl','adriasushi.cl'],mix:['Producto','Historia','Experiencia','Proceso','Venta','Educación'],ideas:[
      ['Proceso','Del armado al plato','Mostrar manos preparando un roll o plato, sin posar.','Toma 45°, manos trabajando, ingredientes reales y mesón limpio.','Enriquecer el contenido con cocina real y oficio.'],
      ['Experiencia','El sushi del barrio se vive aquí','Mostrar el local con personas y ambiente, no solo comida.','Plano amplio del salón o terraza con clientes, sin interrumpir el servicio.','Reforzar barrio, confianza y experiencia.'],
      ['Producto','Más que rolls','Mostrar un plato Thai, ceviche o entrada que tenga poca presencia reciente.','Primer plano natural del plato recién terminado, 45° y algo del local de fondo.','Dar variedad visual y recordar amplitud de carta.'],
      ['Historia','Una escena que cuente Adrià','Rescatar un rincón, objeto o momento que permita contar años de barrio.','Foto espontánea de Rafael, Tamara, cocina o fachada trabajando.','Construir marca y memoria, no solo vender.'],
      ['Educación','Explicar algo que el cliente siempre pregunta','Elegir una preparación, ingrediente o diferencia de la carta.','Foto detalle del producto más una segunda toma del proceso.','Crear contenido útil y guardable.'],
      ['Venta','Una razón concreta para pedir hoy','Elegir un producto fuerte y llevarlo a una pieza con CTA claro.','Foto limpia, apetecible y reconocible del producto completo.','Convertir contenido en pedidos sin convertir todo el feed en promociones.']
    ]},
    'adria-sangucheria':{name:'Sanguchería Adrià',sources:['adria.cl','adriasangucheria.cl'],mix:['Producto','Historia','Experiencia','Proceso','Venta','Educación'],ideas:[
      ['Proceso','Plancha en acción','Mostrar cómo se prepara un churrasco, lomito o completo.','Foto o video corto de la plancha con manos trabajando y producto real.','Transmitir fuente de soda viva y oficio.'],
      ['Producto','El clásico que falta mostrar','Elegir entre completos, AS, churrascos o lomitos según lo menos mostrado.','Producto entero, mesa real, 45° y sin exceso de producción.','Ampliar percepción de la carta.'],
      ['Experiencia','Fuente de soda de barrio','Mostrar una mesa servida, barra o momento cotidiano del local.','Plano horizontal o vertical con comida y personas en contexto.','Vender experiencia y cercanía.'],
      ['Educación','¿Qué hace distinto este sánguche?','Explicar ingredientes y lógica de un clásico chileno.','Foto abierta del producto y detalle del relleno.','Dar contexto y generar conversación.'],
      ['Historia','Una fuente de soda con historia Adrià','Conectar Sanguchería con la historia familiar y de barrio.','Fachada, equipo o escena cotidiana sin posar.','Construir confianza más allá del precio.'],
      ['Venta','Antojo con CTA','Elegir un producto de buena rentabilidad o una promoción vigente.','Foto frontal/45° con papas o bebida solo si corresponden realmente.','Mover ventas con una pieza concreta.']
    ]},
    'pet':{name:'Adrià PET',sources:['Instagram @adria.pet'],mix:['Producto','Cuidado','Proceso','Mascotas','Educación','Venta'],ideas:[
      ['Mascotas','El producto en su contexto real','Mostrar una mascota real interactuando con un snack Adrià PET.','Mascota a su altura, luz natural y producto visible sin forzar la escena.','Generar confianza y contenido emocional real.'],
      ['Proceso','De cocina a snack','Mostrar preparación, secado o envasado de un producto.','Detalle de manos, ingrediente y proceso higiénico.','Transmitir transparencia.'],
      ['Producto','Conoce un snack','Elegir un producto y mostrarlo claramente.','Envase + producto fuera del envase sobre fondo simple.','Facilitar comprensión y compra.'],
      ['Educación','Qué estás comprando','Explicar de qué está hecho un snack sin afirmaciones veterinarias.','Macro del ingrediente/producto y envase.','Aportar información útil sin promesas médicas.']
    ]},
    'chef-rafael':{name:'Chef Rafael',sources:['Adrià','Experiencia real del chef'],mix:['Historia','Proceso','Opinión','Aprendizaje','Emprendimiento','Cocina'],ideas:[
      ['Proceso','Lo que estoy haciendo hoy','Mostrar una decisión o trabajo real detrás de Adrià.','Foto espontánea trabajando, probando, costeando o cocinando.','Construir una marca personal creíble.'],
      ['Historia','Una historia detrás de Adrià','Contar un recuerdo concreto usando una foto o lugar real.','Foto antigua o actual del lugar/persona relacionada con la historia.','Conectar experiencia y trayectoria.'],
      ['Aprendizaje','Algo que aprendí operando un restaurante','Partir de un problema real y explicar una conclusión útil.','Rafael en contexto real, no retrato corporativo.','Aportar valor y autoridad desde experiencia.'],
      ['Cocina','El criterio del chef','Explicar por qué una preparación se hace de determinada forma.','Proceso + resultado final.','Mostrar oficio y criterio gastronómico.']
    ]},
    'laberinto-digital':{name:'Laberinto Digital',sources:['Proyectos reales','Casos Adrià'],mix:['Caso real','Educación','Proceso','Sistema','Resultado','Venta'],ideas:[
      ['Caso real','Una automatización que sí usamos','Mostrar una solución implementada realmente en Adrià o una pyme.','Captura limpia del sistema + foto/contexto del negocio.','Demostrar capacidad con evidencia.'],
      ['Educación','Un problema pyme explicado simple','Elegir un problema de marketing, WhatsApp, web o automatización.','Captura, esquema simple o pantalla real.','Aportar utilidad inmediata.'],
      ['Proceso','Así lo construimos','Mostrar antes, decisión y resultado de un proyecto.','2-3 capturas reales del proceso.','Hacer visible el trabajo detrás del servicio.'],
      ['Sistema','Menos tareas repetidas','Mostrar una tarea manual que se pueda ordenar o automatizar.','Foto del proceso real + captura de la solución.','Conectar dolor operacional con servicio.']
    ]}
  };
  const key='laberinto-content-planner-v1';
  const load=()=>{try{return JSON.parse(localStorage.getItem(key))||{};}catch{return {};}};
  const state=load();
  const save=()=>localStorage.setItem(key,JSON.stringify(state));
  const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const recommendations={};
  let recoLoaded=false;
  function ensure(id){state[id]??={cursor:0,done:[],discarded:[]};return state[id];}
  function getIdeas(id,count=4){const cfg=brands[id],s=ensure(id),pool=cfg.ideas.filter((_,i)=>!s.discarded.includes(i));if(!pool.length){s.discarded=[];return getIdeas(id,count);}const out=[];for(let n=0;n<count;n++){const originalIndex=cfg.ideas.indexOf(pool[(s.cursor+n)%pool.length]);out.push({index:originalIndex,data:cfg.ideas[originalIndex]});}return out;}
  async function loadRecommendations(){
    try{const r=await fetch(TIME_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:sessionStorage.getItem(PIN_KEY)||''})}),d=await r.json();if(!r.ok)return;Object.keys(recommendations).forEach(k=>delete recommendations[k]);for(const x of d.items||[]){recommendations[x.brand_id]??={};recommendations[x.brand_id][Number(x.weekday)]??=[];recommendations[x.brand_id][Number(x.weekday)].push(x);}recoLoaded=true;renderTimeChoices();}catch{}
  }
  const localDateValue=(d=new Date())=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
  function selectedWeekday(){const v=document.querySelector('#plannerDate')?.value;if(!v)return new Date().getDay();const [y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d).getDay();}
  function renderTimeChoices(){
    const select=document.querySelector('#plannerTime'),brand=document.querySelector('#plannerBrand')?.value||'adria-sushi';if(!select)return;
    const rows=(recommendations[brand]?.[selectedWeekday()]||[]).sort((a,b)=>a.rank-b.rank),recommended=new Map(rows.map(x=>[Number(x.hour_local),x]));
    const old=select.value;select.innerHTML=Array.from({length:16},(_,i)=>i+8).map(h=>{const x=recommended.get(h),label=`${String(h).padStart(2,'0')}:00${x?x.rank===1?' ★ Mejor':' ★':''}`;return `<option value="${String(h).padStart(2,'0')}:00" ${x?'data-recommended="1"':''}>${label}</option>`;}).join('');
    const preferred=rows[0]?`${String(rows[0].hour_local).padStart(2,'0')}:00`:'';select.value=old&&[...select.options].some(o=>o.value===old)?old:preferred||'13:00';
    const chosenHour=Number(select.value.slice(0,2)),isRecommended=recommended.has(chosenHour);select.classList.toggle('recommended-time',isRecommended);
    const note=document.querySelector('#plannerTimeNote');if(note){const top=rows.slice(0,3).map((x,i)=>`${i===0?'★ ':''}${String(x.hour_local).padStart(2,'0')}:00`).join(' · ');note.textContent=top?`Mejores horas: ${top}`:(recoLoaded?'Usando horario base hasta reunir más historial.':'Cargando mejores horas…');}
  }
  const css=document.createElement('style');css.textContent=`.planner-view{display:none}.planner-view.active{display:block}.planner-toolbar{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.planner-toolbar select{min-width:230px}.planner-schedule{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.planner-schedule label{display:grid;gap:4px;font-size:.72rem;font-weight:800;color:#756b5d;letter-spacing:.03em}.planner-schedule input,.planner-schedule select{min-width:0;width:auto}.planner-time-wrap{display:grid;gap:3px}.planner-time-wrap select.recommended-time{border-color:#9a7a45;background:#fbf5e9}.planner-time-note{font-size:.72rem;color:#9a7a45;min-height:1em}.planner-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.planner-card{background:#fff;border:1px solid #e7dfd2;border-radius:16px;padding:16px;display:grid;gap:10px}.planner-card h3,.planner-card p{margin:0}.planner-tag{font-size:.75rem;font-weight:800;letter-spacing:.04em;color:#756b5d}.planner-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:4px}.mission{border-left:4px solid #111827}.planner-source{font-size:.84rem;color:#756b5d}.planner-note{padding:12px 14px;border-radius:12px;background:#f7f2ea;color:#5f574d}.planner-done{opacity:.58}@media(max-width:760px){.planner-grid{grid-template-columns:1fr}.planner-toolbar{align-items:stretch}.planner-toolbar>select{width:100%}.planner-schedule{width:100%;display:grid;grid-template-columns:1fr 1fr}.planner-schedule input,.planner-schedule select{width:100%}.planner-time-note{grid-column:1/-1}}`;document.head.appendChild(css);
  function boot(){const tabs=document.querySelector('.app-tabs'),shell=document.querySelector('main.main-view'),settings=document.querySelector('#settingsView');if(!tabs||!shell||!settings)return setTimeout(boot,150);if(document.querySelector('#tabPlanner'))return;
    const btn=document.createElement('button');btn.id='tabPlanner';btn.className='app-tab';btn.type='button';btn.textContent='Planificador de contenido';tabs.insertBefore(btn,document.querySelector('#tabSettings'));
    const view=document.createElement('main');view.id='plannerView';view.className='shell planner-view';view.innerHTML=`<section class="panel"><div class="panel-heading"><div><span class="eyebrow">PLANIFICADOR DE CONTENIDO</span><h2>Qué debemos crear y fotografiar</h2></div></div><p class="helper">No es una lista de publicaciones al azar. Busca mantener cada marca variada entre producto, historia, experiencia, proceso, educación y venta.</p><div class="planner-toolbar"><select id="plannerBrand">${Object.entries(brands).map(([id,b])=>`<option value="${id}">${b.name}</option>`).join('')}</select><div class="planner-schedule"><label>Fecha<input id="plannerDate" type="date" value="${localDateValue()}"></label><div class="planner-time-wrap"><label>Hora<select id="plannerTime"></select></label><span id="plannerTimeNote" class="planner-time-note">Cargando mejores horas…</span></div></div><button id="plannerRefresh" class="btn secondary" type="button">Dame otras ideas</button></div><div id="plannerSources" class="planner-note" style="margin-top:12px"></div></section><section class="panel"><div class="panel-heading"><div><span class="eyebrow">ESTRATEGIA</span><h2>Qué debemos publicar</h2></div></div><div id="plannerIdeas" class="planner-grid"></div></section><section class="panel"><div class="panel-heading"><div><span class="eyebrow">PRODUCCIÓN</span><h2>Fotos que necesito tomar</h2></div></div><p class="helper">Abre esta parte cuando estés en el local. Son misiones concretas para producir contenido que hoy falta.</p><div id="plannerMissions" class="planner-grid"></div></section>`;settings.insertAdjacentElement('beforebegin',view);
    function showPlanner(){shell.classList.add('settings-hidden');settings.classList.remove('active');view.classList.add('active');document.querySelectorAll('.app-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');render();renderTimeChoices();}
    btn.addEventListener('click',showPlanner);document.querySelector('#tabPublicador')?.addEventListener('click',()=>view.classList.remove('active'));document.querySelector('#tabSettings')?.addEventListener('click',()=>view.classList.remove('active'));
    document.querySelector('#plannerBrand').addEventListener('change',()=>{render();renderTimeChoices();});document.querySelector('#plannerDate').addEventListener('change',renderTimeChoices);document.querySelector('#plannerTime').addEventListener('change',renderTimeChoices);document.querySelector('#plannerRefresh').addEventListener('click',()=>{const id=document.querySelector('#plannerBrand').value,s=ensure(id);s.cursor+=4;save();render();});render();renderTimeChoices();loadRecommendations();
  }
  function render(){const id=document.querySelector('#plannerBrand')?.value||'adria-sushi',cfg=brands[id],s=ensure(id),items=getIdeas(id,4);document.querySelector('#plannerSources').innerHTML=`<strong>Fuentes y contexto:</strong> ${cfg.sources.map(esc).join(' · ')}<br><strong>Mezcla editorial:</strong> ${cfg.mix.map(esc).join(' · ')}`;
    document.querySelector('#plannerIdeas').innerHTML=items.map(({index,data:d})=>`<article class="planner-card ${s.done.includes(index)?'planner-done':''}" data-i="${index}"><span class="planner-tag">${esc(d[0])}</span><h3>${esc(d[1])}</h3><p>${esc(d[2])}</p><p class="planner-source"><strong>Objetivo:</strong> ${esc(d[4])}</p><div class="planner-actions"><button class="btn secondary mission-btn" data-i="${index}">Ver foto necesaria</button><button class="btn ghost done-btn" data-i="${index}">Ya tengo la foto</button><button class="btn ghost discard-btn" data-i="${index}">Descartar</button></div></article>`).join('');
    document.querySelector('#plannerMissions').innerHTML=items.map(({index,data:d})=>`<article class="planner-card mission ${s.done.includes(index)?'planner-done':''}" id="mission-${index}"><span class="planner-tag">${esc(cfg.name)} · ${esc(d[0])}</span><h3>${esc(d[1])}</h3><p><strong>Toma:</strong> ${esc(d[3])}</p><p class="planner-source">Después de tomarla, vuelve al Publicador y súbela para que la IA prepare el contenido.</p><div class="planner-actions"><button class="btn primary done-btn" data-i="${index}">${s.done.includes(index)?'Foto tomada ✓':'Ya tengo la foto'}</button></div></article>`).join('');
    document.querySelectorAll('.mission-btn').forEach(b=>b.onclick=()=>document.querySelector('#mission-'+b.dataset.i)?.scrollIntoView({behavior:'smooth',block:'center'}));document.querySelectorAll('.done-btn').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.i);if(!s.done.includes(i))s.done.push(i);save();render();});document.querySelectorAll('.discard-btn').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.i);if(!s.discarded.includes(i))s.discarded.push(i);s.cursor++;save();render();});
  }
  boot();
})();