(() => {
  const API='https://ufsxdlmnjuaymdszyjue.supabase.co/functions/v1/laberinto-api';
  const PIN_KEY='laberinto_session_pin';
  let mediaItems=[],analysis=null,dragIndex=null;
  const css=document.createElement('style');
  css.textContent=`
    .ai-publisher{margin-bottom:16px}.ai-grid{display:grid;grid-template-columns:minmax(260px,.9fr) minmax(320px,1.1fr);gap:18px}
    .upload-zone{min-height:250px;border:1px dashed #d6d3cd;border-radius:14px;display:flex;align-items:center;justify-content:center;text-align:center;padding:18px;cursor:pointer;background:#fafaf8}
    .media-stage{display:grid;gap:10px}.media-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.media-card{position:relative;border:1px solid #e6e4df;border-radius:11px;overflow:hidden;background:#fff;cursor:grab}.media-card.dragging{opacity:.45}.media-card img{width:100%;aspect-ratio:1/1;object-fit:cover;display:block}.media-num{position:absolute;left:6px;top:6px;background:rgba(17,17,17,.82);color:#fff;border-radius:999px;font-size:11px;font-weight:800;padding:3px 7px}.media-remove{position:absolute;right:6px;top:6px;border:0;background:rgba(255,255,255,.92);width:26px;height:26px;border-radius:999px;cursor:pointer;font-weight:800}.media-add{border:1px dashed #d6d3cd;background:#fafaf8;border-radius:11px;min-height:92px;cursor:pointer;font-weight:750}.media-hint{font-size:12px;color:#777}.ai-controls{display:grid;gap:11px;align-content:start}.ai-controls label{display:grid;gap:6px;font-weight:650}.ai-controls textarea{width:100%;min-height:145px}.ai-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ai-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.ai-status{font-size:.88rem;color:#737373}
    .ai-badge{padding:4px 8px;border-radius:999px;background:#f1f1ee;font-size:.74rem;font-weight:700}.ai-badge.ok{background:#edf7ef;color:#28613b}.ai-badge.warn{background:#fff3d7;color:#765400}
    .queue-mini{margin-top:16px;border-top:1px solid #e8e8e5;padding-top:15px}.queue-list{display:grid;gap:0}.queue-item{display:grid;grid-template-columns:52px 1fr auto;gap:10px;align-items:center;border-top:1px solid #eee;padding:10px 0}.queue-item:first-child{border-top:0}.queue-thumb{position:relative}.queue-item img{width:52px;height:52px;object-fit:cover;border-radius:9px}.queue-count{position:absolute;right:-3px;bottom:-3px;background:#111;color:#fff;border-radius:999px;font-size:10px;padding:2px 5px}.queue-item small{display:block;color:#777;margin-top:3px}.queue-state{font-size:.72rem;font-weight:800;text-transform:uppercase}.queue-state.failed{color:#a33232}.queue-state.scheduled,.queue-state.publishing,.queue-state.ready,.queue-state.draft{color:#6b5a23}.queue-error{color:#a33232!important}.pin-gate{position:fixed;inset:0;background:rgba(17,24,39,.78);z-index:9999;display:flex;align-items:center;justify-content:center;padding:18px}.pin-card{width:min(420px,100%);background:white;border-radius:18px;padding:24px}.pin-card input{width:100%;font-size:1.1rem;padding:12px;margin:10px 0}
    @media(max-width:780px){.ai-grid,.ai-row{grid-template-columns:1fr}.upload-zone{min-height:190px}.media-grid{grid-template-columns:repeat(3,1fr)}.queue-item{grid-template-columns:46px 1fr}.queue-item>.queue-state{grid-column:2}}
  `;
  document.head.appendChild(css);
  const panel=document.createElement('section');panel.className='panel ai-publisher';panel.innerHTML=`
    <div class="panel-heading"><div><span class="eyebrow">PUBLICADOR IA</span><h2>Fotos → copy → programar</h2></div><div><span id="aiReadyBadge" class="ai-badge warn">IA</span> <span id="igReadyBadge" class="ai-badge warn">Instagram</span></div></div>
    <div class="ai-grid">
      <div class="media-stage"><label class="upload-zone" id="aiUploadZone"><input id="aiFile" type="file" accept="image/jpeg,image/png,image/webp" multiple hidden><div id="aiUploadContent"><strong>Subir foto o carrusel</strong><p class="helper">Elige hasta 10 imágenes</p></div></label><div id="mediaGrid" class="media-grid"></div><button id="addMoreMedia" class="media-add hidden" type="button">+ Agregar fotos</button><div id="mediaHint" class="media-hint"></div></div>
      <div class="ai-controls">
        <div class="ai-row"><label>Marca<select id="aiBrand"><option value="adria-sushi">Adrià Sushi</option><option value="adria-sangucheria">Sanguchería Adrià</option><option value="pet">Adrià PET</option><option value="chef-rafael">Chef Rafael</option><option value="laberinto-digital">Laberinto Digital</option></select></label><label>Idea opcional<input id="aiContext" type="text" placeholder="Ej: producto, historia, evento..."></label></div>
        <div class="ai-actions"><button id="aiAnalyzeBtn" class="btn primary" type="button" disabled>Analizar con IA</button><span id="aiStatus" class="ai-status">Primero sube una o más fotos.</span></div>
        <label>Título<input id="aiTitle" type="text" maxlength="120"></label>
        <label>Texto listo para publicar<textarea id="aiCaption"></textarea></label>
        <div class="ai-row"><label>Fecha y hora<input id="aiSchedule" type="datetime-local"></label><label>Acción<button id="aiScheduleBtn" class="btn primary" type="button" disabled>Programar publicación</button></label></div>
        <div id="aiWarnings" class="helper"></div>
      </div>
    </div>
    <div class="queue-mini"><div class="panel-heading"><div><span class="eyebrow">COLA REAL</span><h3>Pendientes y errores</h3></div><button id="aiRefreshQueue" class="btn ghost" type="button">Actualizar</button></div><div id="aiQueue" class="queue-list"></div></div>`;
  const shell=document.querySelector('main.shell')||document.querySelector('main');shell?.prepend(panel);
  const $=s=>document.querySelector(s),getPin=()=>sessionStorage.getItem(PIN_KEY)||'',status=t=>{const n=$('#aiStatus');if(n)n.textContent=t;};
  const api=async body=>{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,pin:getPin()})});const d=await r.json().catch(()=>({}));if(r.status===401){sessionStorage.removeItem(PIN_KEY);showGate('PIN incorrecto.');throw new Error('PIN incorrecto');}if(!r.ok){const e=new Error(d.error||'Error de conexión');e.code=d.error;e.detail=d.detail;throw e;}return d;};
  const escapeHtml=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const labelStatus=s=>({scheduled:'Programada',publishing:'Publicando',failed:'Error',draft:'Borrador',ready:'Lista'}[s]||s);
  function defaultSchedule(){const d=new Date();d.setDate(d.getDate()+1);d.setHours(13,0,0,0);$('#aiSchedule').value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}defaultSchedule();
  function showGate(message='Ingresa el acceso interno de Laberinto Publicador.'){if(document.querySelector('.pin-gate'))return;const gate=document.createElement('div');gate.className='pin-gate';gate.innerHTML=`<form class="pin-card"><span class="eyebrow">ACCESO INTERNO</span><h2>Laberinto Publicador</h2><p>${message}</p><input id="gatePin" type="password" required placeholder="Código de acceso"><button class="btn primary" type="submit">Entrar</button><p id="gateMsg" class="helper"></p></form>`;document.body.appendChild(gate);gate.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();sessionStorage.setItem(PIN_KEY,gate.querySelector('#gatePin').value.trim());try{await api({action:'status'});gate.remove();await refreshStatus();await refreshQueue();}catch{gate.querySelector('#gateMsg').textContent='No pudimos validar el acceso.';}});}
  async function refreshStatus(){try{const d=await api({action:'status'}),ai=$('#aiReadyBadge'),ig=$('#igReadyBadge'),brand=$('#aiBrand')?.value||'adria-sushi',s=d.instagram_by_brand?.[brand],connected=s?.status==='connected'&&s?.token_ready===true;ai.textContent=d.ai_ready?'IA lista':'Falta IA';ai.className='ai-badge '+(d.ai_ready?'ok':'warn');ig.textContent=connected?((s.instagram_handle?'@'+s.instagram_handle:'Instagram')+' conectado'):'Instagram pendiente';ig.className='ai-badge '+(connected?'ok':'warn');}catch{}}
  function renderMedia(){const grid=$('#mediaGrid'),zone=$('#aiUploadZone'),more=$('#addMoreMedia'),hint=$('#mediaHint');grid.innerHTML=mediaItems.map((m,i)=>`<div class="media-card" draggable="true" data-index="${i}"><img src="${escapeHtml(m.media_url)}" alt="Foto ${i+1}"><span class="media-num">${i+1}${i===0?' · portada':''}</span><button type="button" class="media-remove" data-remove="${i}" aria-label="Quitar">×</button></div>`).join('');zone.classList.toggle('hidden',mediaItems.length>0);more.classList.toggle('hidden',mediaItems.length===0||mediaItems.length>=10);hint.textContent=mediaItems.length>1?`${mediaItems.length} fotos · arrástralas para cambiar el orden · la primera será la portada`:mediaItems.length===1?'1 foto · agrega otra para crear un carrusel':'';grid.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();mediaItems.splice(Number(b.dataset.remove),1);analysis=null;$('#aiScheduleBtn').disabled=true;renderMedia();status(mediaItems.length?'Vuelve a analizar después de cambiar las fotos.':'Primero sube una o más fotos.');}));grid.querySelectorAll('.media-card').forEach(card=>{card.addEventListener('dragstart',()=>{dragIndex=Number(card.dataset.index);card.classList.add('dragging');});card.addEventListener('dragend',()=>{dragIndex=null;card.classList.remove('dragging');});card.addEventListener('dragover',e=>e.preventDefault());card.addEventListener('drop',e=>{e.preventDefault();const target=Number(card.dataset.index);if(dragIndex===null||target===dragIndex)return;const [m]=mediaItems.splice(dragIndex,1);mediaItems.splice(target,0,m);analysis=null;$('#aiScheduleBtn').disabled=true;renderMedia();status('Orden actualizado. Vuelve a analizar para que la IA vea el carrusel en este orden.');});});$('#aiAnalyzeBtn').disabled=mediaItems.length===0;}
  async function uploadOne(file){const form=new FormData();form.append('action','upload');form.append('pin',getPin());form.append('brand_id',$('#aiBrand').value);form.append('file',file);const r=await fetch(API,{method:'POST',body:form}),d=await r.json().catch(()=>({}));if(r.status===401){sessionStorage.removeItem(PIN_KEY);showGate();throw new Error('PIN incorrecto');}if(!r.ok)throw new Error(d.error||'No se pudo subir');return d;}
  async function uploadFiles(files){const allowed=[...files].filter(f=>['image/jpeg','image/png','image/webp'].includes(f.type)).slice(0,10-mediaItems.length);if(!allowed.length)return;analysis=null;$('#aiScheduleBtn').disabled=true;for(let i=0;i<allowed.length;i++){status(`Subiendo ${i+1} de ${allowed.length}...`);mediaItems.push(await uploadOne(allowed[i]));renderMedia();}status(mediaItems.length>1?`Carrusel listo con ${mediaItems.length} fotos. Puedes ordenar y analizar.`:'Foto cargada. Puedes analizarla.');}
  async function analyze(){if(!mediaItems.length)return;$('#aiAnalyzeBtn').disabled=true;status(mediaItems.length>1?'Analizando el carrusel completo...':'Analizando imagen y preparando copy...');$('#aiWarnings').textContent='';try{const d=await api({action:'analyze',brand_id:$('#aiBrand').value,media_urls:mediaItems.map(m=>m.media_url),context:$('#aiContext').value});analysis=d.analysis;$('#aiTitle').value=analysis.title||'';const tags=Array.isArray(analysis.hashtags)&&analysis.hashtags.length?'\n\n'+analysis.hashtags.join(' '):'';$('#aiCaption').value=(analysis.caption||'')+tags;const w=Array.isArray(analysis.warnings)?analysis.warnings.filter(Boolean):[];const cover=analysis.cover_recommendation?`Portada: ${analysis.cover_recommendation}`:'';$('#aiWarnings').textContent=[cover,w.length?'Revisar: '+w.join(' · '):''].filter(Boolean).join(' · ');$('#aiScheduleBtn').disabled=false;status(mediaItems.length>1?'Carrusel analizado. Revisa el orden, copy y fecha.':'Propuesta lista. Revísala y programa cuando quieras.');}catch(e){status((e.message||'Error')+(e.detail?' — '+e.detail:''));}finally{$('#aiAnalyzeBtn').disabled=false;}}
  function resetComposer(){mediaItems=[];analysis=null;$('#aiTitle').value='';$('#aiCaption').value='';$('#aiWarnings').textContent='';renderMedia();defaultSchedule();}
  async function schedule(){if(!mediaItems.length)return;const dt=$('#aiSchedule').value,caption=$('#aiCaption').value.trim();if(!dt){status('Elige fecha y hora.');return;}if(!caption){status('Falta el texto.');return;}const kind=mediaItems.length>1?`carrusel de ${mediaItems.length} fotos`:'publicación';if(!confirm(`¿Programar este ${kind} para ${new Date(dt).toLocaleString('es-CL')}?`))return;$('#aiScheduleBtn').disabled=true;status('Programando...');try{await api({action:'schedule',brand_id:$('#aiBrand').value,title:$('#aiTitle').value,caption,media_items:mediaItems,media_url:mediaItems[0].media_url,media_path:mediaItems[0].media_path,ai_analysis:analysis||{},scheduled_at:new Date(dt).toISOString()});status(mediaItems.length>1?'Carrusel programado.':'Publicación programada.');resetComposer();await refreshQueue();}catch(e){status((e.message||'No se pudo programar')+(e.detail?' — '+e.detail:''));$('#aiScheduleBtn').disabled=false;}}
  async function refreshQueue(){try{const d=await api({action:'list'}),root=$('#aiQueue'),items=(d.items||[]).filter(x=>['scheduled','publishing','ready','draft','failed'].includes(x.status)||Boolean(x.error_message));if(!items.length){root.innerHTML='<p class="helper">No hay publicaciones pendientes ni errores.</p>';return;}root.innerHTML=items.slice(0,20).map(x=>{const count=Array.isArray(x.media_items)&&x.media_items.length?x.media_items.length:(x.media_type==='CAROUSEL_ALBUM'?2:1);return `<div class="queue-item"><div class="queue-thumb"><img src="${escapeHtml(x.media_url||'')}" alt="">${count>1?`<span class="queue-count">${count}</span>`:''}</div><div><strong>${escapeHtml(x.title||x.brand_id)}</strong><small>${x.scheduled_at?new Date(x.scheduled_at).toLocaleString('es-CL'):'Sin fecha'}${count>1?' · Carrusel':''}</small>${x.error_message?`<small class="queue-error">${escapeHtml(x.error_message)}</small>`:''}</div><span class="queue-state ${escapeHtml(x.status)}">${labelStatus(x.status)}</span></div>`}).join('');}catch{}}
  $('#aiFile').addEventListener('change',e=>{if(e.target.files?.length)uploadFiles(e.target.files).catch(err=>status(err.message));e.target.value='';});$('#addMoreMedia').addEventListener('click',()=>$('#aiFile').click());$('#aiUploadZone').addEventListener('dragover',e=>e.preventDefault());$('#aiUploadZone').addEventListener('drop',e=>{e.preventDefault();if(e.dataTransfer.files?.length)uploadFiles(e.dataTransfer.files).catch(err=>status(err.message));});$('#aiAnalyzeBtn').addEventListener('click',analyze);$('#aiScheduleBtn').addEventListener('click',schedule);$('#aiRefreshQueue').addEventListener('click',refreshQueue);$('#aiBrand').addEventListener('change',()=>{analysis=null;refreshStatus();if(mediaItems.length)status('Marca cambiada. Vuelve a analizar las fotos.');});
  renderMedia();if(!getPin())showGate();else{refreshStatus();refreshQueue();}
})();